### ISSUE TITLE
Create a Spatial Query Tool

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#101]
This likely consists of 2 parts. 

1. Expand the [OGC filters in GeoExt3](https://github.com/geoext/geoext3/blob/master/src/util/OGCFilter.js) to include spatial filters. The spatial filters couldbe combined with any other filters on a layer, such as via the grid. 

2. Create a configurable tool(s)
The tool would be configured with an associated layer (in terms of final  UI it would likely be added to a grid toolbar). In terms of priority the initial tool will be for a point layer, selecting with a polygon layer. The tool would be passing a polygon to the WFS and running an Intersects or Within (for points I believe the results would be identical). 

Second priority/example would be a BBOX tool to draw around poygons or polyline layers. This would integrate nicely with the [GeoExt Demo App](http://w08-mapserver.compass.ie/geoext-demo/) and allow selection on the map. 

WFS Spatial Filter references:

* https://mapserver.org/ogc/filter_encoding.html#currently-supported-features
* https://docs.geoserver.org/latest/en/user/filter/filter_reference.html#spatial-operators
* http://docs.opengeospatial.org/is/09-026r2/09-026r2.html#55

**Comment by ahennr** [comment]
Spatial filter are introduces in https://github.com/geoext/geoext3/pull/566/
