### ISSUE TITLE
Add Karma testing to the project

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#105]
Linting is already run on the project as part of CI with Travis and locally with NodeJS. 

Ideally some sample tests will be added using Karma (the suite used in GeoExt), along with all necessary changes to package.json to run these from the command line with Node. 
Some "best practices" on how/what to test are welcomed. 

GeoExt can be used as a template for the testing/linting approach, although only tests and linting are required currently (no need for docs building etc. yet). 

I've gone through the docs at https://github.com/geoext/geoext3/blob/master/development.md which are very useful in going throught the steps on testing locally. 

In addition it would be useful to setup testing for https://github.com/geographika/geoext-demo-app - this is more of an application rather than a library of components, so would be very useful how a GeoExt-based application should be tested.

**Comment by verendi** [comment]
Priority is on Cpsi-mapview

**Comment by ahennr** [comment]
https://github.com/geographika/geoext-demo-app/pull/1

**Comment by ahennr** [comment]
https://github.com/compassinformatics/cpsi-mapview/pull/121

https://github.com/compassinformatics/cpsi-mapview/pull/122

**Comment by geographika** [comment]
Thanks for these. I'll be using them as a template for other projects.
