### ISSUE TITLE
Apply ViewBox to GeocoderComboBox Request

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#109]
The nominatim search allows a viewbox parameter to be sent to limit the results of the search e.g. [Lurgan](
https://nominatim.openstreetmap.org/search.php?q=Lurgan&polygon_geojson=1&viewbox=-247.50000%2C72.81607%2C247.14844%2C-55.77657). 
Ideally the [GeocoderComboBox](https://github.com/geoext/geoext3/blob/master/classic/form/field/GeocoderComboBox.js) would have a config option to take the initialExtent of the map and pass this to all queries.

This would limit the results to the extent of the map and filter out the place names outside the map's area of interest.

**Comment by ahennr** [comment]
Included in `GeocoderComboBox` in GeoExt3, see https://github.com/geoext/geoext3/pull/574

**Comment by geographika** [comment]
Very nice. 
Note to self - I may make a further pull request to GeoExt allowing a fixed extent to be set as part of the config. All this requires is a call to `addMapExtentParams(extent, mv.getProjection());`
