### ISSUE TITLE
Create radio buttons for layer themes

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#111]
The old version of mapview had a class to generate radio buttons for an array of styles associated with a WFS layer. 

![radio_sld](https://user-images.githubusercontent.com/490840/62227195-c234b080-b3bb-11e9-917f-8881135fe121.png)

This allowed switching between different SLD files for the same vector features - [code here](https://github.com/compassinformatics/mapview/blob/master/src/gis/tree/CustomWfsLoader.js)

SLD file names were stored in the layer config file as a comma delimtied list e.g. `"slds": "Collision Type,Accident Type"` in the JSON config file. 
			
			
It would be good to apply similar functionality in the new version of mapview. The feature would also benefit from being compatible with both WFS and WMS. 
For WMS layers the selected STYLE would be sent to the WMS server. 
For WFS the selected SLD file would be applied. Code to apply SLDs to layers is currently [in the LayerFactory](https://github.com/compassinformatics/cpsi-mapview/blob/master/app/factory/Layer.js#L354)

**Note** - if vector tiles work well (see #102) then there is no immediate requirement to support WFS layers. If vector tiles can support 1,000s of features then it may make more sense to allow users to switch styles on vector layers directly?

The config could be a proper list rather than a string e.g. `"styles": ["style1","style2"]`

The same config could be used for WFS referencing SLD files: `"styles": ["style1.xml","style2.xml"]`

The method used to apply the styles must be compatible with `CpsiMapview.view.menuitem.LayerLabels` which adds a label style on top of any existing style.

**Comment by geographika** [comment]
Tested for both WMS and WFS, and with the labels plugin - works perfectly thanks!

I do have a couple of questions (and possibly updates if time permits).

![layertree](https://user-images.githubusercontent.com/490840/63504673-50d7b180-c4d2-11e9-8f7e-dd318160663d.png)

1. Is it possible to update the associated layer legend with the selected style? Currently the layer factory uses a simplistic legendUrl with a hard-coded style. For WMS layers the GetLegendGraphic URL could be dynamically generated based on the WMS URL and selected style. For MapServer at least the same WMS GetLegendGraphic URL would also work for WFS legends. 

2. Is there a CSS class that can be used to reduce the spacing between the list of style options?

**Comment by chrismayer** [comment]
> 1. Is it possible to update the associated layer legend with the selected style? Currently the layer factory uses a simplistic legendUrl with a hard-coded style. For WMS layers the GetLegendGraphic URL could be dynamically generated based on the WMS URL and selected style. For MapServer at least the same WMS GetLegendGraphic URL would also work for WFS legends.

Not sure about this. We should test it. Would you open an issue for this? TIA.

> 2. Is there a CSS class that can be used to reduce the spacing between the list of style options?

I'll have to check. I'll come up with a follow up if no corresponding CSS class is available.
