### ISSUE TITLE
Switch Layer Legend with Style

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#117]
As referred to at #111 

Is it possible to update the associated layer legend with the selected style? The legend would update each time a radio style button is selected.  

Currently the layer factory uses a simplistic legendUrl with a hard-coded style. 
This is then used by `CpsiMapview.plugin.TreeColumnStyleSwitcher` to set the legend in the tree. 

For WMS layers the GetLegendGraphic URL could be dynamically generated based on the WMS URL, parameters, and selected style. For MapServer at least the same WMS GetLegendGraphic URL would also work for WFS legends.

![layertree](https://user-images.githubusercontent.com/490840/63576921-87263700-c58d-11e9-9993-06f2e240061f.png)

**Comment by chrismayer** [comment]
> For MapServer at least the same WMS GetLegendGraphic URL would also work for WFS legends.

Could you provide an example for a WFS GetLegendGraphic request in MapServer?

https://plmonaghandev.compass.ie/mapserver/?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetLegendGraphic&FORMAT=image%2Fpng&TRANSPARENT=TRUE&SLD_VERSION=1.1.0&LAYER=LightUnit&STYLE=LightUnit_Unit_Type.xml

brings `msWFSDispatch(): WFS server error. Invalid WFS request: GetLegendGraphic`

**Comment by geographika** [comment]
I can use a naming convention for the XML style exports and the style name in this case LAYERNAME_STYLENAME 
I previously replaced any spaces in the stylename with underscores - but I can work around this.

**Comment by chrismayer** [comment]
> I previously replaced any spaces in the stylename with underscores - but I can work around this.

Oh if that is the convention I can work with that. So for WMS

LAYERS: `LightUnit` 

and

STYLE:  `Unit Types` 

become 

`LightUnit_Unit_Type.xml` (`LAYERS_STYLE<with underscores>.xml`) for WFS, correct? If yes I can implement this already.

**Comment by geographika** [comment]
@chrismayer - yes that is the convention I was using. Good news!

**Comment by geographika** [comment]
@chrismayer - very nice!
I have one question -  why do the layers require a legendWidth or legendHeight defined for the layer?
I tried without and there are some very cryptic ExtJS errors and requests to undefined URLs, so I know it must be fixing this, but not sure why.

**Comment by chrismayer** [comment]
Hmm. My thought was that the layer config should have an indicator if it should use the automatic `getLegendGrapic` URL or not (to avoid any legend). Giving a `legendWidth` or `legendHeight` and no `legendUrl` seemed to be an easy indicator with existing properties. Alternatively a new config property `useAutoLegend` or similar would be also possible.

Avoiding the  `legendWidth` or `legendHeight` should not bring any exceptions. At least I could not reprodice it. Can you please post your layer config here?

**Comment by geographika** [comment]
@chrismayer - a couple of integration issues addressed in #134 
I'll probably consider a `useAutoLegend` for a future release. Setting the legend dimensions caused stretching of images. 
All good for deployment tomorrow!
