### ISSUE TITLE
Adding Jsonix to the project

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#118]
When working with WFS layers (as part of #116) the `handleWfsExecuteException` uses `BasiGX.util.Jsonix` on the line below. Without adding Jsonix as a dependency unmarshaller in the line is null. 

`            var parsedXml = util.unmarshaller.unmarshalString(response);		// unmarshaller here is null`

There is a console message that:

> Missing Jsonix library. BasiGX.util.Jsonix will not work as expected.

I've tried adding in the [v3 lib from GitHub](https://raw.githubusercontent.com/highsource/jsonix/master/dist/Jsonix-min.js) but I'm still getting:

`
Uncaught Error: Element [{http://www.opengis.net/ows}ows:ExceptionReport] could not be unmarshalled as is not known in this context and the property does not allow DOM content.
`

Are there instructions on how best to add the library for example in BasiGX? Or a reason for the above error?

**Comment by ahennr** [comment]
The reason for this error is that jsonix / the module factories (here: OWS_1_1_0) aren't loaded in the application. I've added all required jsonix dependencies in #130 to cpsi-mapview.

In addition, I've enhanced documentation of `BasiGX.util.Jsonix` in https://github.com/terrestris/BasiGX/pull/505 to make this clearer for future projects / usages.

**Comment by geographika** [comment]
@ahennr - thanks for the explanation and docs update
