### ISSUE TITLE
Windows Toolbar and Minimizable Windows

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#147]
## Overview

The old system allowed windows to be minimised to a "toolbar" - an area at the bottom of the map. These windows could then be restored.
This concept and code was based on the [ExtJS Desktop Example App](https://examples.sencha.com/extjs/6.7.0/examples/classic/desktop/) (version 4) but is still maintained and available in ExtJS 6.x

![image](https://user-images.githubusercontent.com/490840/66759164-02c2a700-eea0-11e9-80f6-67bb5ea7377a.png)

Windows could then have the following properties set:

```
        maximizable: true,
        minimizable: true,
        collapsible: false,
```

Relevant classes in the old codebase:

- [Compass.pms.ux.AbstractTaskBar](https://github.com/compassinformatics/pmsjs/blob/master/src/app/ux/AbstractTaskBar.js)
- [Compass.pms.ux.TaskButton](https://github.com/compassinformatics/pmsjs/blob/master/src/app/ux/TaskButton.js)
- [Compass.pms.utils.BaseFormWindow](https://github.com/compassinformatics/pmsjs/blob/master/src/app/utils/BaseFormWindow.js)
- [TaskButtonsPanel](https://github.com/compassinformatics/pmsjs/blob/master/src/app/ux/TaskButtonsPanel.js)

In addition a "Minimise All" button was available on the toolbar. 

See also various Ext.ux classes such as `Ext.ux.desktop.TaskBar`
## Design Options

- Create as a separate module? See similar choice required for #142 
- Add as a mixin to Windows rather than a base class?

**Comment by jansule** [comment]
I created a new window class in the cpsiMapview application, that enables the functionality you requested (minimizable into toolbar). However, this comes with the limitation that only windows created in the cpsiMapview app are minimizable. Windows that were created in dependencies (e.g. GeoExt, BasiGX) are not affected.

Using mixins did not work out, as they cannot be added to the class/instance on runtime (we would have to extend the Ext.window.Window class to add the mixin there, which is kind of the same thing as above). Also, this would have the same limitation as above.

There might be another way of forcefully injecting this feature to all windows (incl those of dependencies) via Ext.override. But that will probably lead to side effects (e.g. minimizable alerts).

@geographika is the ability of minimizing windows sufficient for only those windows that were created in the application directly?

**Comment by geographika** [comment]
@jansule - thanks for this. 
I don't think there is any issue only allowing this for windows created by the application. 
Do you have any examples in the cpsi-mapview project where windows are created by GeoExt/BasiGX that can't be overridden with an application specific window?

**Comment by jansule** [comment]
@geographika thanks for the feedback.

Currently, there do not seem to be any windows created by GeoExt/BasiGX that should be minimizable. I found usages of `BasiGX.util.MsgBox` which also creates windows, but these were used as alerts so far, so they should not be minimizable.

So it's more a just-in-case thing.
