### ISSUE TITLE
Allow a default projection to be set on basigx-panel-coordinatemouseposition

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#160]
Allow a default setting for the [coordinatemouseposition](http://terrestris.github.io/BasiGX/master/docs/#!/api/BasiGX.view.panel.CoordinateMousePositionPanel). E.g.

```
{
        xtype: 'basigx-panel-coordinatemouseposition',
        epsgCodeArray: ['EPSG:4326', 'EPSG:29902', 'EPSG:2157'],
        defaultCode: 'EPSG:2157',
        segmentedButtonLimit: 3
}
```

**Comment by chrismayer** [comment]
I opened a PR in the BasiGX repository for this: https://github.com/terrestris/BasiGX/pull/582
