### ISSUE TITLE
Improve Karma Browser Debugging Speeds

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#162]
Review of testing process when running in a browser e.g. when using:

`karma start --browsers Chrome --single-run=False --debug --auto-watch`

And navigating to http://localhost:9876/debug.html

This is used to manually test and experiment with UI components. 

Page reloads are very slow, with each code file loaded one at a time. 
Review if the testing approach can be improved. This would also have implications for geoext. 
Setup of the pmsjs project may be required to illustrate this issue. A screen-sharing session would likely be required.

**Comment by jansule** [comment]
Performance might be improved by configuring Karma to not run all tests, but rather only those tests in the spec file you are currently changing.

See
- https://github.com/webpack-contrib/karma-webpack/pull/258
- https://github.com/webpack-contrib/karma-webpack/pull/258#issuecomment-321266234
- https://github.com/aaronjensen/karma-webpack

The linked PR was never merged, so the described configurations would have to be done manually.

If the general performance of the tests is bad, it could also be a windows issue. On linux, the performance seems to be fine (for the basic tests included in this project).

Generally, using a non-headless browser slows down the performance.

**Comment by geographika** [comment]
@jansule - thanks for looking into this. 

The cpsi-mapview tests actually ok - they take ~8 seconds to load all required files. See output from Chrome below. Do you get similar results?

For larger projects based on mapview it is the sheer number of files loaded one after the other that means ~20 seconds to run even a single test (it appears all spec dependencies are loaded even if only a single test is run). 

![chrome_debugger](https://user-images.githubusercontent.com/490840/75963982-b87da900-5ec6-11ea-8bc7-56fd6c97fe13.png)

**Comment by jansule** [comment]
@geographika Could you give me a more detailed description on how exactly you run the tests (or a single test)? So we have a similar setup for comparison.

In the project directory I run 
```
node_modules/karma/bin/karma start --browsers Chrome --single-run=False --debug --auto-watch
```
(I don't have karma installed globally) and ALL specs will be automatically tested. This takes about 2-3 seconds.

**Comment by geographika** [comment]
@jansule - I've uploaded a video showing the debugging in the browser, and reloading the page: https://streamable.com/xjaos
Do you get similar speeds?

**Comment by geographika** [comment]
I've found the cause of this - it is the use of `Ext.Loader.syncRequire` at the top of test files. 
For small projects this is fine, but in larger ones these calls cause all application dependencies to be loaded one by one and has a dramatic effect on load times. 

Measuring using Powershell, adding a single `Ext.Loader.syncRequire` to the top of a test file to include a form with several custom components caused total test times to change from ~7s to ~13s. 

`Measure-Command { karma start --single-run }`

The only issues with removing the syncRequire are:

- numerous ` [Ext.Loader] Synchronously loading` warnings in the test output
- needing to use `Ext.create('...` to create all components for testing

**Comment by marcjansen** [comment]
Are you developing on windows, Seth?

**Comment by geographika** [comment]
Closing as speeds much better when `Ext.Loader.syncRequire` not used.
