### ISSUE TITLE
Use GeoStyler libs via npm 

### ISSUE THREAD

**Issue by chrismayer** [compassinformatics/cpsi-mapview#182]
The GeoStyler libs used in here (geostyler-openlayers-parser & geostyler-sld-parser) are currently manually created browser builds and thus not updateable easily. In the meantime the GeoStyler and its related projects (e.g. parsers) are available at [npm](https://www.npmjs.com/search?q=keywords:geostyler), so we should use them via npm to have an automatic update strategy for the GeoStyler libs used.

TODOs:

- Add corresponding entries to `dependencies` in package.json
- Reference the browser build files from `node_modules` in the `js` section in the `app.json`

**Comment by geographika** [comment]
Closed with #193
