### ISSUE TITLE
WFS layer ruins does not support sorting

### ISSUE THREAD

**Issue by chrismayer** [compassinformatics/cpsi-mapview#212]
When opening the Data Grid for the layer "Ruins" via context menu the backend server returns the following error: 

```
<ows:Exception exceptionCode="OperationProcessingFailed" locator="mapserv">
    <ows:ExceptionText>msWFSGetFeature(): WFS server error. Layer ruins does not support sorting</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
```

**Comment by geographika** [comment]
There is a bug somewhere in MapServer with the OGR layer. I can have filtering via the native MapServer shapefile connection or sorting with the OGR connection - so not both. 
I'm currently investigating and posted to the [mailing list](https://lists.osgeo.org/pipermail/mapserver-users/2020-March/081643.html).

**Comment by geographika** [comment]
Fixed with https://github.com/MapServer/MapServer/pull/6156 and updates to https://github.com/compassinformatics/mapview-demo
