### ISSUE TITLE
GAS WFS returns exeception

### ISSUE THREAD

**Issue by chrismayer** [compassinformatics/cpsi-mapview#214]
The GAS WFS used in the app responds with an exception, which seems to be related to the OGC filter sent:

[Request](https://ows.terrestris.de/geoserver/osm/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&OUTPUTFORMAT=application%2Fjson&TYPENAME=osm%3Aosm-fuel&SRSNAME=EPSG%3A3857&FILTER=%3Cogc:Filter%20xmlns:ogc=%22http://www.opengis.net/ogc%22%3E%20%3Cogc:BBOX%3E%20%3Cgml:Envelope%20xmlns:gml=%22http://www.opengis.net/gml%22%20srsName=%22EPSG:3857%22%3E%20%3Cgml:lowerCorner%3E-909753.5106501678%207083725.159300424%3C/gml:lowerCorner%3E%20%3Cgml:upperCorner%3E-717437.9474846643%207236599.215870777%3C/gml:upperCorner%3E%20%3C/gml:Envelope%3E%20%3C/ogc:BBOX%3E%20%3C/ogc:Filter%3E)

OGC Filter used (pretty printed):
```xml
<ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
    <ogc:BBOX>
        <ogc:PropertyName></ogc:PropertyName>
        <gml:envelope xmlns:gml="http://www.opengis.net/gml" srsName="EPSG:3857">
            <gml:lowerCorner>-909753.5106501678 7083725.159300424</gml:lowerCorner>
            <gml:upperCorner>-717437.9474846643 7236599.215870777</gml:upperCorner>
        </gml:envelope>
    </ogc:BBOX>
</ogc:Filter>
```

Reponse:

```xml
<ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://ows.terrestris.de/geoserver/schemas/ows/1.1.0/owsAll.xsd">
<ows:Exception exceptionCode="XML getFeature request SAX parsing error" locator="org.geoserver.ows.XmlRequestReader">
<ows:ExceptionText>
org.xml.sax.SAXException: Attempted to construct illegal filter - I dont understand the tag: gml:Envelope. HINT: tags are case-sensitive! Attempted to construct illegal filter - I dont understand the tag: gml:Envelope. HINT: tags are case-sensitive!
</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
```
The [code herefore](https://github.com/compassinformatics/cpsi-mapview/blob/master/app/factory/Layer.js#L378) has not been changed for month and worked a few days ago for @jansule and me while working on recent issues. So maybe a backend issue?

**Comment by geographika** [comment]
Closed with #216
