### ISSUE TITLE
Legend items disappear

### ISSUE THREAD

**Issue by select-8** [compassinformatics/cpsi-mapview#229]
Legend items disappear if the item text contains more than 33 characters (possibly the feature symbol has an effect on this number). 
Even when text does display, if you close the slider, on reopening they will disappear. This will happen with anything above 27 characters.
<img width="395" alt="Screenshot 2020-04-23 at 11 09 43" src="https://user-images.githubusercontent.com/47751242/80089040-43893000-8555-11ea-8751-23962af5f4c0.png">

**Comment by JakobMiksch** [comment]
@geographika I am trying to reproduce the bug, but I am not sure if I understand correctly.

The screenshot indicates that the radio buttons for the styles are missing. However, meanwhile these radio buttons have moved inside the context menu of the layer. Therefore this problem would not apply anymore.

The name of the item is cut of by 27 characters. See:

![image](https://user-images.githubusercontent.com/15704517/121537743-7cf45780-ca04-11eb-81dc-9db7a6d9bed9.png)

or 

![image](https://user-images.githubusercontent.com/15704517/121537900-a01f0700-ca04-11eb-92c4-168280904d53.png)

This could for exampel be solved by hovering of the layer and displaying its full name.

**Comment by geographika** [comment]
@JakobMiksch  - the radio buttons UI is unlikely to come back so is not an issue. 
However if the layer legend is beyond a certain width it gets hidden completely. The following can be recreated by setting the following line to have a width of `180`:

https://github.com/compassinformatics/cpsi-mapview/blob/2ff75bd7f98d0fec285a84fb88dd5419221322dc/app/view/main/Main.js#L30

![image](https://user-images.githubusercontent.com/490840/121598069-aed7df00-ca41-11eb-8fde-0681fc48ab8c.png)

I've tried adding various combinations of layouts and `scrollable: true` but can't seem to force at least a scrollbar to appear. 
After some more experimenting, simply adding `resizable: true` to the Tools panel seems to be a good enough fix.
