### ISSUE TITLE
Layer metadata tree plugin

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#240]
Create a new [tree plugin](https://github.com/compassinformatics/cpsi-mapview/blob/master/app/plugin/TreeColumnContextMenu.js) that adds a new "Layer Metadata" menu option. 

When clicked this will do the following:

1. Create request based on layer name (assume all layers have metadata rather than requiring a flag in layers.json)
2. Get metadata XML from server
3. Populate grid based on metadata name/value pairs and open in window

MapServer is used as the backend. 
GetMetadata support was implemented in https://mapserver.org/development/rfc/ms-rfc-82.html
A sample request is: http://my.host.com/cgi-bin/mapserv?request=GetMetadata&layer=foo

MapServer’s layer API supports the [ISO 19115:2003 geospatial standard](https://www.iso.org/standard/26020.html)

**Comment by geographika** [comment]
@geographika - add sample request and decide key fields.

**Comment by geographika** [comment]
For this release there will be 3 fields used for the metadata plugin. 
For reference, I have added in the property in the Mapfile each XML path is set by: 

- identificationInfo > MD_DataIdentification > citation > CI_Citation title (maps to MapServer "ows_title")
- identificationInfo > MD_DataIdentification > abstract > CharacterString (maps to MapServer "ows_abstract")
- identificationInfo > MD_DataIdentification > descriptiveKeywords > MD_Keywords (maps to  MapServer"ows_keywordlist") - can be concatenated to comma separated list


I will add metadata to all the layers in the demo MapServer service.
A finished example request is: https://w08-mapserver.compass.ie/mapserver/?map=/MapServer/apps/mapview-demo/example.map&&REQUEST=GetMetadata&layer=ruins

**Comment by chrismayer** [comment]
The 3 metadata fields should be presented in a [PropertyGrid](https://docs.sencha.com/extjs/6.2.0/classic/Ext.grid.property.Grid.html) which is in a floating window.
