### ISSUE TITLE
Add Clear Features option to Network Solver

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#252]
Add a context menu option "Clear Features" to remove all lines and points created by the Network Solver tool.

![image](https://user-images.githubusercontent.com/490840/87691793-4b8af180-c78b-11ea-9f0b-00b5c5291742.png)

Use to clear active group only, or all features if 1 group.

**Comment by simonseyock** [comment]
@geographika How can the network solver tool be accessed in the demo application?

**Comment by geographika** [comment]
@simonseyock - this is only setup for roads in County Tipperary. Then use the Point tool to create paths. 

![image](https://user-images.githubusercontent.com/490840/96420760-30020d80-11f6-11eb-9ff7-f06c30950b90.png)


![image](https://user-images.githubusercontent.com/490840/96420699-195bb680-11f6-11eb-8271-1c87cad05bb6.png)
