### ISSUE TITLE
Drag and drop points with the Network Solver Tool

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#253]
This tool is a variant of the [DigitizeButtonController](https://github.com/compassinformatics/cpsi-mapview/blob/master/app/controller/button/DigitizeButtonController.js). 
Functionality could be created either as a subclass, a mixin to the current tool, or as configurable options on the current tool. 

It will allow a user to click points on the map to create a route as in the existing tool. Once the line has been created the tool will allow a user to select and drag the end points of the line, and then drop them. This will call the service again and return a new line feature. 

To add in conjunction with #88?

![image](https://user-images.githubusercontent.com/490840/87692323-eb487f80-c78b-11ea-91df-8e3ea52ebb6e.png)

**Comment by simonseyock** [comment]
To achieve this and the delete button, I think it would be best to keep track of all drawn points and in which order they were drawn and which lines belong to which drawn point.

If this is done, it would actually also be possible to modify or delete points in between, not only the last point.

At the moment every time a new point is drawn all segments get recalculated. This actually is not necessary, or is it?

**Comment by simonseyock** [comment]
Only the last part between the previous drawn point and the new point can change, is that true?

**Comment by simonseyock** [comment]
After some thinking I came to the conclusion that recalculating everything should also be possible. This will result in more requests to the tool, though. What is the preferred way?

Is the network solver open source? Or is there a detailed documentation of the api?

**Comment by simonseyock** [comment]
So I actually implemented it using the same method like before. You can ignore the above questions.

I did some refactoring of the class, though. Now the functions can be used in a more modular way which is useful for the modification.
