### ISSUE TITLE
switchlayer not changing when in a subfolder

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#265]
The following layer search code will need to be made to be recursive to check for overlays within overlays: https://github.com/compassinformatics/cpsi-mapview/blob/master/app/factory/Layer.js#L926

**Comment by chrismayer** [comment]
Maybe http://terrestris.github.io/BasiGX/master/docs/#!/api/BasiGX.util.Layer-static-method-getAllLayers is good option here to determine the layers.

**Comment by geographika** [comment]
Reusing this function would make sense to me. 
There are a few places where layer searches are made: https://github.com/compassinformatics/cpsi-mapview/search?q=getLayers
I think a couple of these might also benefit from using this function.
