### ISSUE TITLE
Demo service for ruins not fully working

### ISSUE THREAD

**Issue by chrismayer** [compassinformatics/cpsi-mapview#296]
The demo service for ruins seems to be not fully working:

The WFS GetFeature returns exceptions:

https://w08-mapserver.compass.ie/mapserver/?map=/MapServer/apps/mapview-demo/example.map&&SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&OUTPUTFORMAT=application%2Fjson&TYPENAME=ruins&SRSNAME=EPSG%3A3857&FILTER=%3Cogc%3AFilter%20xmlns%3Aogc%3D%22http%3A%2F%2Fwww.opengis.net%2Fogc%22%3E%20%20%3Cogc%3ABBOX%3E%20%20%20%20%3Cogc%3APropertyName%3EmsGeometry%3C%2Fogc%3APropertyName%3E%20%20%20%20%3Cgml%3AEnvelope%20xmlns%3Agml%3D%22http%3A%2F%2Fwww.opengis.net%2Fgml%22%20srsName%3D%22EPSG%3A3857%22%3E%20%20%20%20%20%20%3Cgml%3AlowerCorner%3E-1042448.1917532338%206969528.239042371%3C%2Fgml%3AlowerCorner%3E%20%20%20%20%20%20%3Cgml%3AupperCorner%3E-641612.4154257695%207285060.291803579%3C%2Fgml%3AupperCorner%3E%20%20%20%20%3C%2Fgml%3AEnvelope%3E%20%20%3C%2Fogc%3ABBOX%3E%3C%2Fogc%3AFilter%3E

```xml
<?xml version="1.0" encoding="UTF-8"?>
  <ows:ExceptionReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ows="http://www.opengis.net/ows/1.1" version="2.0.0" xml:lang="en-US" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd">
  <ows:Exception exceptionCode="OperationProcessingFailed" locator="mapserv">
  <ows:ExceptionText>msWFSGetFeature(): WFS server error. FLTApplyFilterToLayer() failed
  msOGRFileNextShape(): OGR error. OGR GetNextFeature() error'd. Check logs.</ows:ExceptionText>
  </ows:Exception>
  </ows:ExceptionReport>
```

**Comment by chrismayer** [comment]
Needed for the implementation of #245

**Comment by geographika** [comment]
Fixed with https://github.com/MapServer/MapServer/pull/6156
