### ISSUE TITLE
Create a Panel Expander Mixin

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#321]
Create a reusable mixin or plugin that allows a panel to be expanded to fill the viewport, or a parent component, such as the centre region of the viewport.

This would work in the same way as the "Maximize example code content" button found in the ExtJS kitchen sink example: https://examples.sencha.com/extjs/6.7.0/examples/kitchensink/?classic#window-variations

![image](https://user-images.githubusercontent.com/490840/96640392-638e8600-1323-11eb-88bf-960c495d96ee.png)

This does not appear to be a part of a framework, but instead uses a "ghost" panel and fills this with the component when the "Maximize" button is clicked. 

A Sencha Fiddle link with similar functionality: https://fiddle.sencha.com/#view/editor&fiddle/1juu

**Comment by chrismayer** [comment]
You linked the ExtJS v6.7 kitchen sink app. Since we are on v6.2 we should use this link https://examples.sencha.com/extjs/6.2.0/examples/kitchensink/?classic#window-variations to see only the features we can use in here.

**Comment by simonseyock** [comment]
I looked into this. For windows it is quite trivial: just set `maximizable` to true.
For other panels it gets complex. The problem is that the elements have to be moved into another container and this can cause tons of side effects. I tried it but I was not very successful.
Here is the code I tested it with: https://github.com/compassinformatics/cpsi-mapview/blob/expand-panel/app/plugin/ExpandPanel.js

**Comment by geographika** [comment]
@simonseyock - thanks for looking at this. 
The use-case is we have a grid with lots of columns on a form. It would be useful to expand this to edit then close and go back to the form. 

The large window can cover the rest of the application - so could be thought of as a modal window so the original grid would not have to be removed if that helps at all. 

This old thread seems to suggest it would work that way: https://forum.sencha.com/forum/showthread.php?271445-Move-a-component-from-one-panel-to-another

What is an example of a side-effect? Lots of JS errors?

**Comment by simonseyock** [comment]
Yes, I suppose some of them have to do with specialized layouts.

Maybe in your case you have no side effects appear. You can try the plugin in the branch mentioned above. It is as easy as adding a plugin with `ptype: 'cmv_expand_panel'`. It should then add a tool with type `maximizable` to the panel (maybe difficult to see - I did not figure out yet why it does not show the icon).

At the moment I try to copy the children of the panel. But another possibility would be to copy the element itself - this could result in duplicated headers. But maybe it does not cause that many errors.

**Comment by chrismayer** [comment]
Maybe moving / copying the component itself to the maximized window (with layout ``fit) is worth giving a shot. Just an idea, did not test it.

**Comment by simonseyock** [comment]
This could be then configured like this:
```
{
  xtype: 'cmv_expand_panel`,
  items: {
    xtype: 'Ext.panel.Panel',
    // ....
    tools: [{
      type: 'maximize',
      handler: function () {
          this.up('cmv_expand_panel').expand();
      }
  }]
}
```

**Comment by simonseyock** [comment]
The problem is that I am not in the office tomorrow and probably can not continue to work on this.

**Comment by geographika** [comment]
@simonseyock - thanks for the prototype. The `remove` caused strange layout errors, but moving the full component seemed to work (at least the expand part), but as you mentioned has a duplicate header. I'll continue investigating on this branch.

**Comment by simonseyock** [comment]
I was able to try my idea I posted above, but it does not work because you can not drop in any wrapper, because sometimes components of a certain type are expected. Another idea I had was that the plugin would get a parent panel and target position of the item as config options. This only works for panels, not containers, though.

**Comment by geographika** [comment]
@simonseyock - I like the idea of keeping it as a plugin and set the parent as a config option (maybe defaulting to the immediate parent using `.up()`)?

**Comment by simonseyock** [comment]
@geographika I think I got a working solution, but you have to check if it works under your specific circumstances as well.

It should just work if you add a plugin with `ptype: 'cmv_expand_panel` to a panel with a direct parent that is also a panel.
