### ISSUE TITLE
Missing style radio button setting for switch layer change 

### ISSUE THREAD

**Issue by chrismayer** [compassinformatics/cpsi-mapview#326]
As stated in #319 by @geographika there is a minor issue (edge case) for the SwitchLayer:

"One minor issue in the mapview testing - the style radio buttons is not always set/retained when switching layers:

![image](https://user-images.githubusercontent.com/1185547/96881028-1ffc5f00-147e-11eb-8663-6b311b376b89.png)

In the larger project I get an error when zooming in and out. It could be related to the same issue above - the WMS style is not set when the application is started up and the map zoomed in."

"Error thrown [here](https://github.com/compassinformatics/cpsi-mapview/pull/319/files/2e1810aa47d1bf3b51f21d5373ac607808b82fa7#diff-3dcce41425692865fc9f197d93d4455a6ba113982a7e65ae5db1bd8d2347f2b0R967) as activeStyle is undefined. This is when the application starts zoomed in, and the switch layer is off by default, and then zoomed out so the WMS takes over. This happens if all switch layers are switched off and the map is simply zoomed in and out."

**Comment by geographika** [comment]
Closing this as unlikely to go back to the radio button UI approach.

**Comment by chrismayer** [comment]
I agree that the approach is very unlikely to come back since it does not scale very well. So should we think about cleaning up the code for the radio buttons directly rendered in the tree node?
