### ISSUE TITLE
Allow point solver to add points on existing feature

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#348]
Currently, clicking on an existing point won't trigger a solve request. This means a full circle cannot be created (which is useful for drawing features on roundabouts). 

![image](https://user-images.githubusercontent.com/490840/101496951-aefc0280-396a-11eb-9881-2309017382ba.png)

See video at https://drive.google.com/file/d/1Rl5sfH_lFTIk18mLVs4rn1kzzuY3EslP/view

This related to the [DigitizeButtonController](https://github.com/compassinformatics/cpsi-mapview/blob/master/app/controller/button/DigitizeButtonController.js). 

Unclear if a handler has to be added to the Draw or Modify interactions.

**Comment by simonseyock** [comment]
The case had to be added to the PointerInteraction, which was only used for delete previously. I renamed it to `pointerInteraction`.
