### ISSUE TITLE
Gazetteer Layers not appearing in the map

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#352]
Relates to #70 

The layers are correctly added to the map at https://github.com/geoext/geoext3/blob/master/classic/form/field/GeocoderComboBox.js#L217 and when a feature is selected it is added to the layer https://github.com/geoext/geoext3/blob/master/classic/form/field/GeocoderComboBox.js#L370

However the layer itself is not visible (although its visible property is `true`). Adding the layer again to the map manually seems to fix this. The feature is therefore not highlighted, as it was previously in the image below. 

![image](https://user-images.githubusercontent.com/490840/101741512-6fe4c300-3aca-11eb-9cfb-71268d630322.png)

I believe it may be related to the loading of the layers into the layer tree at https://github.com/compassinformatics/cpsi-mapview/blob/master/app/controller/LayerTreeController.js#L217

**Comment by simonseyock** [comment]
My solution to this would be to instead replace the layergroup of the map, add the layertree layergroup as a child to the existing layergroup. This way all previously added layer stay there. Also this makes it easier to distinguish if a layer should be displayed in the tree and all the `displayInLayerSwitcher` logic can be removed. I tried this out and it seems to do the trick.
