### ISSUE TITLE
Multiple Switch Layers not loading correctly

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#390]
When two switchlayers are added layers are removed from the map and disassociated with the layer tree nodes. All works fine with a single switchlayer. 

I believe the following may be the key to finding the issue. Running `overlayCollection.getLength()` after the following call returns a count of one less than before - the first layer is removed by the `setAt` but the second layer is never added to the map. Trying to manually add the `newLayer` at this stage also fails to add the layer (but no warning or error):

https://github.com/compassinformatics/cpsi-mapview/blob/833ba027154bd6856f08eb097a0839eb7885c6ec/app/factory/Layer.js#L1021

I believe it may have something to do with the event handlers being triggered in `GeoExt.data.store.LayersTree` - `addLayerNode` etc. but suspending the events below caused similar issues with layers becoming disassociated with nodes.

```
        var treePanel = Ext.ComponentQuery.query('treepanel')[0];
        var treeStore = treePanel.getStore();
        treeStore.suspendCollectionEvents();
```

**Comment by geographika** [comment]
Screencast showing the issue at https://drive.google.com/file/d/1u9L9d77MrOcArXx4qHvysRXUOwQYS2TY/view
The layers fail to load when zooming in and triggering the switch to WFS (also happens the other way round). 

Removing one of the switch layers (from [default.json](https://github.com/compassinformatics/cpsi-mapview/blob/master/resources/data/layers/default.json) fixes the issue, and everything works again. 

Fixing the issue is also a chance to possibly refactor some [code duplication](https://github.com/compassinformatics/cpsi-mapview/blob/ec6bae254558e006de2cb013f121edf243ab5427/app/factory/Layer.js#L1009), and attempt to add some automated tests to the test suite.

**Comment by JakobMiksch** [comment]
it seems to me that the problem occurs when the information of one layer in the layer tree is opened. When the information is closed, even both switch layers work without problem.

**Comment by geographika** [comment]
@JakobMiksch - by "information opened" - do you mean the legend is visible for the layer (tree node expanded)?

**Comment by JakobMiksch** [comment]
@geographika yes, when you click on the `+` in the layer tree. See image below.
![image](https://user-images.githubusercontent.com/15704517/118481342-a971c800-b713-11eb-90a2-94c1bc1654ac.png)

**Comment by JakobMiksch** [comment]
@geographika I discovered the problem only occurs if a switchlayer is **alone** in a group. 
It works well if it is in the main group or if there is at least one other (non-group)-layer inside its group.

example, with the configuration in this `tree.json` both switch layers work like they should:

```json
[...]
       "children": [
           {
            "title": "My Group",
            "expanded": false,
            "children": [
              {
                "id": "BOREHOLE_WMS",
                "leaf": true,
                "text": "Borehole WMS"
              },
              {
                "id": "BOREHOLE_WFS",
                "leaf": true,
                "text": "Borehole WFS (Time)",
                "qtip": "Filter records with the timeslider control"
              },
              {
                "id": "RUINS_WFS",
                "leaf": true,
                "text": "Ruins",
                "qtip": "Right-click for a layer grid"
              }
            ]
          },
          {
            "id": "WATERBODY_SWITCH_LAYER_FAR",
            "leaf": true,
            "text": "Waterbody Switch Layer (far)"
          },
          {
            "id": "WATERBODY_SWITCH_LAYER_CLOSE",
            "leaf": true,
            "text": "Waterbody Switch Layer (close)"
          },
          {
            "id": "GAS_WFS",
            "leaf": true,
            "text": "GAS WFS"
          }
        ]
[...]
```
![image](https://user-images.githubusercontent.com/15704517/118655615-ffb13a80-b7e9-11eb-8c33-bfe6c0e404d9.png)

**Comment by JakobMiksch** [comment]
Additionally I found out that a switch-layer must not be the last in a group, then it seems to work fine. 
The problem seems to be somewhere in the connection of the tree store and the layer group.

**Comment by geographika** [comment]
I think it may be related to the overlay count being off by one at:

https://github.com/compassinformatics/cpsi-mapview/blob/833ba027154bd6856f08eb097a0839eb7885c6ec/app/factory/Layer.js#L1021

Are you able to recreate in a unit test?

**Comment by JakobMiksch** [comment]
@geographika thanks for your comment. Meanwhile I created a PR for this #408

**Comment by JakobMiksch** [comment]
@geographika in the `tree.json` the switchlayers are in separate groups. I am not sure if this is intentionally. This is actually not necessary. Switchlayers can also be in the top-level overlay group among with other layers. It is only required to both add them to `tree.json` like here:

```json
[...]
        {
            "id": "COUNTRY_WFS",
            "leaf": true,
            "text": "Country WFS",
            "qtip": "An OSM based WFS layer"
          },
          {
            "id": "OSM_WMS",
            "leaf": true,
            "text": "OSM WMS",
            "qtip": "An OSM based WMS layer",
            "iconCls": "map"
          },
          {
            "id": "BOREHOLE_WMS",
            "leaf": true,
            "text": "Borehole WMS"
          },
          {
            "id": "BOREHOLE_WFS",
            "leaf": true,
            "text": "Borehole WFS (Time)",
            "qtip": "Filter records with the timeslider control"
          }
[...]
```

**Comment by JakobMiksch** [comment]
@simonseyock also found a suspicious line in `GeoExt` 
https://github.com/geoext/geoext/blob/f4c4b252d13e6737f4c4da9437eee09067132327/src/data/store/Layers.js#L330

@geographika  @chrismayer maybe this is also a part of the underlying issue
