### ISSUE TITLE
Full-screen mode has gaps on IE11

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#400]
When putting the map in full screen mode there are black margins on the right and bottom of the map:

![image](https://user-images.githubusercontent.com/490840/117655253-1c6cc300-b197-11eb-9af2-0acafb673e1b.png)

**Comment by simonseyock** [comment]
I looked into this and it seems that somehow the extjs size calculation is working against the openlayers styles from the fullscreen control. As there way to many classes and styles that could possibly interfere. I don't know if I will be able to find a solution in a reasonable amount of time.

**Comment by geographika** [comment]
Thanks @simonseyock - good to know. Please leave this issue for now, and we'll work on trying to drop IE11 support instead!

**Comment by geographika** [comment]
IE11 is still currently supported, but we won't be spending time fixing issues with workarounds, or UI glitches.
