### ISSUE TITLE
Feature store two-way binding

### ISSUE THREAD

**Issue by simonseyock** [compassinformatics/cpsi-mapview#411]
For Issue https://github.com/geoext/geoext/issues/653 I created a fix https://github.com/geoext/geoext/pull/686 which would be a breaking change. It might be possible to create a fix that is not breaking, but that would be a rather messy solution.

For geoext there soon will be a version 4.0.0 with openlayers. We could easily integrate it there. Would that be an option?

**Comment by geographika** [comment]
Once https://github.com/geoext/geoext/pull/693 is merged this can be closed.
