### ISSUE TITLE
Update createFeatureStore to use new 2-way feature bindings

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#416]
Now https://github.com/compassinformatics/cpsi-mapview/issues/411 is resolved using https://github.com/geoext/geoext/pull/686 the [CpsiMapview.model.FeatureStoreMixin[https://github.com/compassinformatics/cpsi-mapview/blob/master/app/model/FeatureStoreMixin.js] can be simplified. 

Once the new collections approach is added to:

https://github.com/compassinformatics/cpsi-mapview/blob/6e297c19e59ec8d5042fc3dff8faf2f19fc8e7dd/app/model/FeatureStoreMixin.js#L78

It should be fine to remove all listeners:

https://github.com/compassinformatics/cpsi-mapview/blob/6e297c19e59ec8d5042fc3dff8faf2f19fc8e7dd/app/model/FeatureStoreMixin.js#L102

The mixin is added to models using an approach similar to below

```js
Ext.define('CpsiMapview.model.Example', {
    extend: 'Ext.data.Model',

    mixins: {
        eventsMixin: 'CpsiMapview.model.FeatureEventsMixin',
        features: 'CpsiMapview.model.FeatureStoreMixin'
    },

    proxy: {
        type: 'rest',
        url: '/WebServices/example',
        reader: {
            rootProperty: 'data'
        },
        writer: {
            writeAllFields: true
        }
    },
    idProperty: 'featureId',
    requires: [
        'CpsiMapview.field.Polygon',
        'CpsiMapview.field.Line',
        'Ext.data.validator.Presence',
        'Ext.data.validator.Inclusion'
    ],

    fields: [
        {
            name: 'featureId',
            type: 'int',
            defaultValue: null,
            persist: false
        },
            {
            name: 'edges', // server expects an array of measures in the edges property
            type: 'edges',
            defaultValue: null,
            featureStoreConfig: {
                lineColor: '#339900',
                pointColor: '#33FF00'
            },
            mapping: 'segmentFeatures', // server sends GeoJSON with this property name
            validators: [
                {
                    type: 'pms_arrayvalidator',
                    min: 1
                }
            ]
        },
        {
            name: 'zoneGeometry3857',
            type: 'polygon'
        }
    ]
});
```

**Comment by simonseyock** [comment]
I removed the mentioned code and added an test In the mentioned commit above. I pushed this directly to the `update-ol` branch. Is that ok? Or should I rather open PRs against the branch for every issue?

**Comment by geographika** [comment]
Seems fine to me to add to `update-ol` branch.
