### ISSUE TITLE
Add Reset Filters context-menu option

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#417]
Add an option on the context-menu for a layer to `Reset Filters`. This would include both attribute and spatial filters set in the grid, and would likely need to call:

https://github.com/compassinformatics/cpsi-mapview/blob/6e297c19e59ec8d5042fc3dff8faf2f19fc8e7dd/app/controller/grid/Grid.js#L588

If there are no filters then the menuitem should be disabled. If there is no associated grid it should not appear at all. 

With the introduction of #410 it is also possible for a layer/grid to have default preset filters. If this is the case then rather than removing all filters it would revert to the preset filters (so probably simplest to add this logic to the `clearFilters` function linked to above). If a user wants to see all data they can still manually remove all filters from the grid. 

The option would be created using the same approach as for other layer context menus e.g. https://github.com/compassinformatics/cpsi-mapview/blob/master/app/view/menuitem/LayerRefresh.js

![image](https://user-images.githubusercontent.com/490840/120645390-aea37680-c478-11eb-99d4-c9481bbe127b.png)

**Comment by JakobMiksch** [comment]
@geographika a question:
when there is a layer with a grid and preset filters. Should the button "Reset Filters" only be shown, when the preset filters are currently **not** applied?

**Comment by geographika** [comment]
I think if there are preset filters it should always be shown. If it is easy to disable the menuitem when only preset filters are applied that would be good to have but not essential.
