### ISSUE TITLE
Reference sponsorship of features in base libraries

### ISSUE THREAD

**Issue by marcjansen** [compassinformatics/cpsi-mapview#42]
We should reference the sponsor when we add or change stuff in GeoExt or BasiGX.

**Comment by geographika** [comment]
@marcjansen - you gave Compass plenty of credit in the last FOSS4G talk! Will close this issue. There might be enough updates in GeoExt, cpsi-mapview, and BasiGX to have content for a FOSS4G talk next year (will also see about ExtJS 7 updates).

**Comment by marcjansen** [comment]
Thank you! Looking forward to anything in that direction
