### ISSUE TITLE
Sync map feature selections with grid selections

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#421]
The `CpsiMapview.controller.button.DigitizeButtonController` based tools allow selection of records in a grid which selects features in the map. In the screenshot below the second grid record is selected, and it is automatically highlighted in red on the map. 

![image](https://user-images.githubusercontent.com/490840/121031156-65ba2d80-c7aa-11eb-81ce-4232e05383b6.png)

This is handled with:

https://github.com/compassinformatics/cpsi-mapview/blob/6e297c19e59ec8d5042fc3dff8faf2f19fc8e7dd/app/controller/button/DigitizeButtonController.js#L1097

It would be useful to also be able to select features in the map to update the selection in the grid. This would likely require the layer to have onClick events, which would prevent the digitising tool being triggered again. 

If there is an approach that would allow a generic mixin to be added to automatically sync grid and layer selections to GeoExt then this would be ideal (similar to the store/layer synching in https://github.com/geoext/geoext/pull/683). 

For testing the point digitising tool can be used to select roads in Tipperary - https://compassinformatics.github.io/cpsi-mapview/#map=19/-877886.9/6894435.27/0

**Comment by simonseyock** [comment]
@geographika I will look into it. Right away I would say it could get a little difficult to add another click event on the geometries. There is already a snapping to the points and deleting on click. It could get squeezed in there I think, but would be also ok to just hightlight in the grid when the feature is hovered in the map?

The tool seems to be quite broken for me in regard to deleting points. Should I investigate?

**Comment by simonseyock** [comment]
Also every second click does not seem to work.

**Comment by simonseyock** [comment]
This was a problem related to the ol update.

**Comment by geographika** [comment]
@simonseyock - are the clicks not working in the latest master or the ol6 branch? The point events were working when https://github.com/compassinformatics/cpsi-mapview/pull/356 was tested. 

It seems ok in https://compassinformatics.github.io/cpsi-mapview/#map=17/-877951.77/6894592.88/0

**Comment by geographika** [comment]
Just missed your comment!

>Right away I would say it could get a little difficult to add another click event on the geometries. There is already a snapping to the points and deleting on click. It could get squeezed in there I think, but would be also ok to just hightlight in the grid when the feature is hovered in the map?

I've just noticed I haven't setup the selections to work between grid -> features in the demo app. I'll look at that now as I have it working in applications using mapview. 

Ideally, the user should click the lines to select records in the grid. A hover select would remove any grid selection which could be confusing. OL2 used to have a selection object/concept, but I believe this is gone in OL3+?

**Comment by geographika** [comment]
Might be best to get https://github.com/compassinformatics/cpsi-mapview/pull/412 merged now to avoid merge conflicts?

**Comment by simonseyock** [comment]
Well in OL3 there is the select interaction, but I would not recommend using it. Even one of the core developers of openlayers discourages the use of it. It is possible but a little tricky.

**Comment by simonseyock** [comment]
I don't know if you want #412 already merged, there will surely be some more bugs. But it would speed up the process of finding them ...

**Comment by geographika** [comment]
I'm +1 for merging now, to both speed up finding any other issues and avoiding merge conflicts with future development. I can also push a new demo to https://compassinformatics.github.io/cpsi-mapview/
Not sure how this would impact @JakobMiksch ?

**Comment by geographika** [comment]
Re the selctions does `GeoExt.selection.FeatureModelMixin` already support the 2-way selections? Is it a case of correctly configuring the selection model on the grid?

```js
    selModel: {
        type: 'featuremodel',
        mode: 'SINGLE',
        allowDeselect: true,
        mapSelection: true,
        selectStyle: new ol.style.Style({
            image: new ol.style.Circle({
                radius: 10,
                stroke: new ol.style.Stroke({
                    color: '#0ff',
                    width: 3
                })
            }),
            stroke: new ol.style.Stroke({
                width: 3,
                color: '#0ff'
            })
        }),
        bind: {
            map: '{map}'
            // TODO can't bind to a formula in the ViewModel
            //selectStyle: '{selectStyle}'
        }
    },
```

**Comment by JakobMiksch** [comment]
Good question. I was about to write that #410 could be merged from my side, and to suggest to move the remaining task "apply preset filters on app start"  as separate issue.

**Comment by simonseyock** [comment]
For me it is fine to merge #410 first.

About the selection model: This would be the nicest approach. It will maybe get tricky to stop the digitize button from handling the click. I look into it.

**Comment by simonseyock** [comment]
I added this: https://github.com/geoext/geoext/pull/690
which I think is necessary as the lines are very thin.
