### ISSUE TITLE
Investigate use of debounce approach for The GeoExt.data.store.WfsFeatures

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#422]
The GeoExt.data.store.WfsFeatures aborts requests when loading for the reasons oulined at https://github.com/geoext/geoext/pull/589 and https://github.com/geoext/geoext/issues/550

See: https://github.com/geoext/geoext/blob/0e6df60ea3e9ed169181e610e502d7efbcd0fa86/src/data/store/WfsFeatures.js#L388

This approach prevents older calls overwriting newer calls, but it does still hit the server twice with sometimes very heavy WFS requests. 

The commit https://github.com/compassinformatics/cpsi-mapview/commit/38129e746c04477a373bca85deafa99e0428612e introduced image aborting (#402) - perhaps this approach would be a better solution than simply aborting a request?

**Comment by simonseyock** [comment]
In general I would say that debouncing is the better solution to these kind of problems. It solves the problem of many successive requests in not doing many requests in the first place. I will look into this.

**Comment by simonseyock** [comment]
By the way: The demo wfs seems to be down:
https://w08-mapserver.compass.ie/mapserver/?map=/MapServer/apps/mapview-demo/example.map&SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&OUTPUTFORMAT=application%2Fjson&TYPENAME=ruins&SRSNAME=EPSG%3A3857&FILTER=%3Cogc%3AFilter%20xmlns%3Aogc%3D%22http%3A%2F%2Fwww.opengis.net%2Fogc%22%3E%20%20%3Cogc%3ABBOX%3E%20%20%20%20%3Cogc%3APropertyName%3EmsGeometry%3C%2Fogc%3APropertyName%3E%20%20%20%20%3Cgml%3AEnvelope%20xmlns%3Agml%3D%22http%3A%2F%2Fwww.opengis.net%2Fgml%22%20srsName%3D%22EPSG%3A3857%22%3E%20%20%20%20%20%20%3Cgml%3AlowerCorner%3E-1011531.3649590448%207025501.8654699%3C%2Fgml%3AlowerCorner%3E%20%20%20%20%20%20%3Cgml%3AupperCorner%3E-859852.5683340754%207104841.5437044995%3C%2Fgml%3AupperCorner%3E%20%20%20%20%3C%2Fgml%3AEnvelope%3E%20%20%3C%2Fogc%3ABBOX%3E%3C%2Fogc%3AFilter%3E

**Comment by geographika** [comment]
@simonseyock - our servers are currently offline and may not be back until later today.
