### ISSUE TITLE
Add Icon to Coordinate Center Tool

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#487]
cpsi-mapview uses the `BasiGX.view.panel.CoordinateMousePositionPanel` in the bottom toolbar:

https://github.com/compassinformatics/cpsi-mapview/blob/7becdc33cb590a6546ef05e9986244d390c7b6a0/app/view/toolbar/MapFooter.js#L22

![image](https://user-images.githubusercontent.com/490840/131339067-eabfad0f-f7bf-4e1a-87fc-eb0a284533ff.png)

The old mapview UI included assitional functionality to place an icon at the centre of the map when using the coordinate tool. The icon could then be click to remove it from the map - see gif:

![Pavement Management System](https://user-images.githubusercontent.com/490840/131339289-3998b75c-ed58-490e-b137-8539619c10c8.gif)

The `BasiGX.view.panel.CoordinateMousePositionPanel` could be subclassed to add this functionlality (or added as an option to the BasiGX component?).

**Comment by jansule** [comment]
Partially solved in https://github.com/terrestris/BasiGX/pull/699

**Comment by jansule** [comment]
Fully solved with https://github.com/compassinformatics/cpsi-mapview/pull/589
