### ISSUE TITLE
Allow Line geometry offsets to be created

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#569]
Add functionality to allow a new geometry to be displayed as an offset of an original line geometry.

Use case:

- A user will select a stretch of road. This will be returned by the Python routing tools as a new OL line feature
- A user will be able to create a new line as an offset of the original (to mark-up cycle tracks)

One possible option is to have number selectors on the UI that shift the new line geometry dynamically to the left or right of the line (or are 4 boxes needed to offset in 4 directions)?

![image](https://user-images.githubusercontent.com/490840/176154993-5a4efeb2-b4a8-4115-a038-e81f732d95fe.png)

![image](https://user-images.githubusercontent.com/490840/176155450-4084d3cc-7925-44a5-94ae-cd1113470bf9.png)

Review existing approaches in desktop GIS for possible UI implementations:

https://desktop.arcgis.com/en/arcmap/latest/manage-data/creating-new-features/creating-a-segment-parallel-to-another-segment.htm

https://gis.stackexchange.com/questions/229914/creating-parallel-lines-at-particular-distance-from-lines-which-are-part-of-a-sh

https://github.com/stdonn/ParallelLineConstruction

**Comment by jansule** [comment]
@geographika Are there any limitations for adding additional javascript dependencies to the project? I was thinking about adding [turf.js lineOffset](https://turfjs.org/docs/#lineOffset) (MIT license), for not having to (re-)implement the offsetting logic by myself.

**Comment by geographika** [comment]
@jansule - it looks like just this function can be added using `npm install @turf/line-offset` - is this correct?
The bulk of the code is https://github.com/Turfjs/turf/blob/master/packages/turf-line-offset/index.js
I think if this works well and is fully-tested it makes sense to use this package (and add to package.json?).

**Comment by jansule** [comment]
> it looks like just this function can be added using npm install @turf/line-offset - is this correct?

Yes, this is correct.

> I think if this works well and is fully-tested it makes sense to use this package (and add to package.json?).

Alright, thanks. I will add this to package.json and will update app.json accordingly.

**Comment by geographika** [comment]
Thanks @jansule - closing.
