### ISSUE TITLE
Request minimum required fields for WFS Layers

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#628]
An example WFS layer configuration (used in `default.json`) is shown below:

```
  {
    "layerType": "wfs",
    "layerKey": "MYLAYER_WFS",
    "geometryProperty": "msGeometry",
    "featureType": "MyLayer",
    "serverOptions": {
      "propertyname": "Field1,Field2,Field3
    },
    "styles": [
      {
        "name": "style1.xml",
        "label": "style1_Label.xml",
        "title": "Style 1"
      },
      {
        "name": "style2.xml",
        "label": "style2_Label.xml",
        "title": "Style 2"
      }
     ],
    "tooltipsConfig": [
      {
        "alias": "Field1",
        "property": "Field1"
      },
      {
        "alias": "Field2",
        "property": "Field2"
      }
     ]
```

This will request the WFS layer with a `PROPERTYNAME` parameter containing the list of fields in `serverOptions` > `propertyname` e.g. "Field1,Field2,Field3". The backend (MapServer) can then limit the fields it requests from a database view to just these fields. If `serverOptions` > `propertyname` is not set then all fields are requested. Only requesting the exact list of fields required can sometimes make a noticeable difference in download speed. 

Currently `serverOptions` > `propertyname` needs to contain _all_ the fields used by the tooltips configuration _and_ all the fields used in all the SLD styles configured for the layer. 

In layers with many SLD styles (e.g. ~10), then all WFS requests include all 10 fields, even though typically only 1 fields is actually required for the client-side styling. 

![image](https://user-images.githubusercontent.com/490840/210967192-f1e74ed6-7b63-495f-9bdc-8a673d19b46e.png)

Switching styles causes a new server WFS request (although if all fields are present I'm not sure if/why this is required). 

Two possible optimistations seem possible:

- instead of setting `serverOptions` > `propertyname` "manually" in the config, build the exact list of required fields. This would include all `property` values from `tooltipsConfig` objects, and all properties required for the selected style. The style object would need to be modified to list these fields e.g.

```
      {
        "name": "style1.xml",
        "label": "style1_Label.xml",
        "properties": "Field1,Field3,LabelField"
        "title": "Style 1"
      },
```

Properties would need to be a comma-separated string as an SLD could make use of several properties for styling, and the associated `label` SLD file could also include additional fields. 

A backend scrript (Python) could parse the SLD files and create these fields lists automatically by searching for property names. 

The JS would then check the requested style and concatenate the tooltips and style properties, remove any duplicates, and set the `propertyname` to send as the WFS request. 

A second possible optimisation is when switching styles to check if the fields used for the newly selected style are already present in the OL layer. If the values are already available client-side then there should be no requirement to make a new server request.

**Comment by fergaldoyle** [comment]
@geographika on the point that a new WFS request is made each time a style is selected, it seems that is caused by this line.

https://github.com/compassinformatics/cpsi-mapview/blob/f7310451c24e29a9d6248f57a20ba36810beb311/app/factory/Layer.js#L996

Commenting out this line prevents the new WFS request, and the style is applied as expected. 

Another optimization would be to cache the style XML file once it is fetched. Currently the XML file is fetched each time you select a style, even if it has been selected previously.

**Comment by fergaldoyle** [comment]
The second option you mentioned above would be straightforward to implement:

1. Define exact list of field names used in tooltip and default style in `serverOptions.propertyname`
2. Each time a style xml is loaded, check what fields are used in that style (by checking for ogc:PropertyName nodes, or checking GeoStylerSLDParser output)
    -  If fields referenced in the style have already been set in step one, skip `source.refresh()` and let the style be applied to the current map features
    - If fields referenced in the style have *not* already been set in step one, update the propertyname list to include missing fields, and call `source.refresh()` to perform a WFS request to get data with all required fields

Step 1 could be manual or could be automated with python.

**Comment by fergaldoyle** [comment]
Setting `disableCaching: false` does indeed disable cache busting and default browser caching takes care of the rest.
