### ISSUE TITLE
editorconfig line endings setting

### ISSUE THREAD

**Issue by fergaldoyle** [compassinformatics/cpsi-mapview#640]
The line ending setting in `.editorconfig` is set to `lf`` but the majority of js files are `crlf`. 

If you are using EditorConfig within your IDE, on save the file will be automatically converted to use `lf`. This can lead to diffs which show the whole file has changed instead of the actual lines of change, making PRs difficult to review.

Not sure what the best setting is here. Probably 85% of the files are `crlf` with the remaining `lf`. Probably removing `end_of_line ` from  `.editorconfig` will allow the IDE choose the line endings for the file currently being edited.

**Comment by geographika** [comment]
@fergaldoyle - could you make a pull request with the change to .editorconfig?
Longer term it is probably best to standardise on `lf`, but it is going to mess up the git history somewhat.

**Comment by fergaldoyle** [comment]
See https://github.com/compassinformatics/cpsi-mapview/pull/641

Using `.gitattributes`  with `* text=auto` file to normalize line endings across operating systems might be the way to go in future:
 https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=windows
