### ISSUE TITLE
Port StreetView Tool

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#71]
The current mapview project includes a custom OpenLayers2 tool that allows a user to click a point on a map which opens up a window with the Google StreetView for that location. A user can then move around the StreetView window and a corresponding marker icon on the main map moves in synch. 

Current code: https://github.com/compassinformatics/mapview/blob/master/src/gis/StreetViewTool.js
and https://github.com/compassinformatics/mapview/blob/master/src/gis/StreetViewToolAction.js

There may be issues with integrating Google with the new version of OpenLayers. 
The StreetView tool requires the blue lines displaying where StreetView is available rather than the Google base maps. It is currently unclear if these can be used directly without full Google/OpenLayers integration. 

The following library may be useful as a dependency: https://github.com/mapgears/ol3-google-maps

TO SEND - google API key

**Comment by geographika** [comment]
The current implementation works vey well, and was easy to inegrate into another project. 
One minor display issue was that the SV controls are hidden by the ExtJS window title as shown below:

![image](https://user-images.githubusercontent.com/490840/58412518-e8199e00-8076-11e9-9f3e-bdb270995902.png)

**Comment by chrismayer** [comment]
Correct, I could reproduce the layout issue and I opened a PR (#96) to fix this.

**Comment by geographika** [comment]
Tested and integrated - thanks @chrismayer !
