### ISSUE TITLE
Implement FeatureSelectionModel for Grids

### ISSUE THREAD

**Issue by chrismayer** [compassinformatics/cpsi-mapview#98]
Create an equivalent to the `FeatureSelectionModel` of previous GeoExt versions, e.g.  https://geoext.github.io/geoext2/docs/#!/api/GeoExt.selection.FeatureModel in GeoExt3.
This avoids that every grid needs to manually setup a map interactions and listeners.

**Comment by geographika** [comment]
Thanks @chrismayer  - this will also cutdown on several lines of code in the OSGeoLive QuickStart when officially released.
